name: Test Automation WorkFlow

on:
  schedule:
    - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Test logs
        path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Test Reports
        path: report.html
        
    - name: Upload Screenshot as Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Screenshots
        path: screenshots/        

    - name: Test Execution status
      if: always()    
      run: echo "Test Execution Completed"

    - name: Copy Reports to gh-pages Folder
      if: always()

      run:  |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l
        
    
    - name: Deploy to GitHub Pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secret.PAT1234 }}
        clean: true

      

      


    


    
